version: "3.8"
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7331:3003"
    environment:
      # inject on secret... 
      - ENVIRONMENT=

      - SERVER_NAME=
      - SERVER_PORT=
      - SECRET_KEY=

      - JWT_EXPIRED_DAY=
      - STAY_ALIVE_MINUTE=

      - MONGO_URL=
      - MONGO_NAME=

      - DB_TYPE=
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_MIGRATION=

      - RABBIT_URL=

    # volumes:
    #   # setup file or folder
    #   - /home/cloufina/service-name/assets:/app/assets
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
