version: "3.8"
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7331:3003"
    environment:
      # inject on secret... 
      - SERVER_NAME=
      - SECRET_KEY=

      - MONGO_URL=
      - MONGO_NAME=

    # volumes:
    #   # setup file or folder
    #   - /home/cloufina/service-name/assets:/app/assets
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
